### ISSUE TITLE
serial.serialutil.SerialException: could not open port 'COM1': PermissionError(13, 'Access denied.', None, 5)

### ISSUE THREAD

**Issue by McLavish** [Bhagyarsh/usim800#1]
Python version: 3.8.1

When running the following instruction:
gsm = sim800(baudrate=115200, path="COM1")

due to this code:
        super().__init__(*args, **kwargs)
        self.requests = request(baudrate=self._baudrate,path=self._path)
        self.info = info(baudrate=self._baudrate,path=self._path)
        self.sms = sms(baudrate=self._baudrate,path=self._path)

the base class "communicate" is instantiated four times, throwing an Access denied exception (you can't open the same port four times)

**Comment by Bhagyarsh** [comment]
have you tried running python in administrator mode

**Comment by McLavish** [comment]
Yes I tried but it didn't change anything. I debugged the code and the Serial.serial method gets called four times, so that must be the issue.

**Comment by Bhagyarsh** [comment]
I haven't tried this module with windows environment. I'll get back to you after I solve this issue.

**Comment by john-arvid** [comment]
I am experiencing the same problem.
I can use the serial library normally, I even tried to recreate the same call that Communicate.py uses and it works.

One thing that I could see was that it runs the command on line 13 in Communicate.py one time successfully before crashing the next time.
I tested this by writing a print('hello') on line 12 in Communicate.py

Hope this can be of some help.

**Comment by john-arvid** [comment]
Just a quick followup.

It looks like it does not close the previous serial connection properly (on windows). I tried to have a serial connection open in another application and then Communicate.py crashes the first time with the same error message.

**Comment by McLavish** [comment]
See my quick hotfix here https://github.com/Bhagyarsh/usim800/pull/2

**Comment by john-arvid** [comment]
Still an issue with some variables not defined.

**Comment by McLavish** [comment]
Yeah, sorry. For some reason, I forgot to push def __init__(self, baudrate, path): to the repo when I made the merge request. Looks like you've fixed it though.

**Comment by john-arvid** [comment]
No worries, good to know I used the same solution as you. But I think this issue is solved now.

**Comment by Bhagyarsh** [comment]
Hi @john-arvid  @McLavish ,
Thanks for fixing this module for windows!
