### ISSUE TITLE
Request new PyPi release

### ISSUE THREAD

**Issue by recolic** [Bhagyarsh/usim800#8]
Hi Team,

My PR to parse the received SMS has been merged at 2022.9. But it was not included in `pip install usim800` yet.

I noticed there is a TODO item `read sms` in PyPi README doc. Could you create a new release so this workitem could be resolved?

Thanks!
https://pypi.org/project/usim800/#history

**Comment by Bhagyarsh** [comment]
Hi  @recolic,
I'm excited to announce that I'm planning a major update to the library soon! Stay tuned for new features and improvements to the codebase. The library is undergoing a revamp! You can expect to see significant changes and additions to the codebase shortly.
Thanks for your contribution! I'm planning to incorporate your changes and other improvements into the codebase,
If you have any suggestions for the revamp, feel free to share them in the discussions!
I'm open to feedback! Let me know if you have any ideas for improvements.
Thanks!
